version: '3.1'
services:
  server:
    container_name: atomspace_server
    env_file:
      - ./server/.env.production
    build: ./server
    volumes:
      - ./server/static:/app/app/static
      - ./server/media:/app/media
    ports:
      - 8000:8000
    command: gunicorn -w 4 config.wsgi -b 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    container_name: atomspace_postgres
    image: postgres:10.1-alpine
    env_file:
      - ./server/.env.production
    volumes:
      - /usr/local/share/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
