version: "3.7"
volumes:
  static:
  media_folder:

services:
  # client:
  #   container_name: atomspace_client
  #   build: ./client
  #   image: atomspace_client
  #   ports:
  #     - "3000:3000"

  server:
    build:
      context: server/
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./app:/app
      - static:/static
      - media_folder:/media_folder
    ports:
      - 8000:8000
    command: gunicorn -w 4 config.wsgi -b 0.0.0.0:8000

  nginx:
    build:
      context: server/
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media_folder:/media_folder