version: '3.1'
services:
  server:
    container_name: atomspace_server
    env_file:
      - ./server/.env
    build: ./server
    volumes:
      - ./server/static:/app/static
      - ./server/media:/app/media
    ports:
      - 8000:8000
    command: bash configure.sh
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    container_name: atomspace_postgres
    image: postgres:10.1-alpine
    env_file:
      - ./server/.env
    volumes:
      - /usr/local/share/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  localstack:
    container_name: atomspace_localstack
    image: localstack/localstack
    env_file:
      - ./server/.env
    ports:
      - 4567-4584:4567-4584
      - 3444:3444
    volumes:
      - /tmp/localstack:/tmp/localstack
